name: portfolio_website
description: Developer Portfolio Website
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  youtube_player_iframe: ^4.0.4
  flutter_staggered_animations: ^1.1.1
  universal_html: ^2.2.4
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  
  # Firebase dependencies (fixed versions, not ranges)
  firebase_core: 2.15.1
  firebase_core_web: 2.7.0
  firebase_auth: 4.7.3
  firebase_auth_web: 5.6.3
  cloud_firestore: 4.8.5
  cloud_firestore_web: 3.6.4
  firebase_analytics: 10.4.5
  firebase_analytics_web: 0.5.4+5

  # Image loading
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  
  # Form validation
  email_validator: ^2.1.17
  
  # SEO
  seo_renderer: ^0.6.0

dependency_overrides:
  firebase_core_platform_interface: 4.8.0
  firebase_auth_platform_interface: 6.16.0
  cloud_firestore_platform_interface: 5.15.0
  firebase_analytics_platform_interface: 3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # For web deployment
  flutter_web_plugins:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/projects/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300